#!/usr/bin/env python3
"""
Post-process a character spritesheet generated by Gemini.

Takes a 4x7 grid spritesheet with a green (#00FF00) chroma-key background and:
1. Removes the background via chroma keying (replaces with transparency)
2. Splits into per-state horizontal strip PNGs (4 frames each)
3. Each frame is resized to exactly 128x128px

Usage:
  python3 scripts/process_spritesheet.py <input_image> <character_key> [--bg-color RRGGBB] [--tolerance N]

Example:
  python3 scripts/process_spritesheet.py /tmp/sausage_raw_sheet.png sausage
"""

import argparse
import sys
from pathlib import Path

from PIL import Image
import numpy as np

# Animation states in row order (7 rows, 4 frames each)
ANIM_STATES = ["idle", "walk", "punch", "kick", "jump", "block", "ko"]
COLS = 4
ROWS = 7
FRAME_SIZE = 128
OUTPUT_DIR = Path(__file__).resolve().parent.parent / "public" / "assets" / "sprites"


def hex_to_rgb(hex_str: str) -> tuple[int, int, int]:
    hex_str = hex_str.lstrip("#")
    return (int(hex_str[0:2], 16), int(hex_str[2:4], 16), int(hex_str[4:6], 16))


def chroma_key(img: Image.Image, bg_color: tuple[int, int, int], tolerance: int) -> Image.Image:
    """Replace pixels close to bg_color with transparency."""
    rgba = img.convert("RGBA")
    data = np.array(rgba)

    r, g, b = bg_color
    dist = np.sqrt(
        (data[:, :, 0].astype(float) - r) ** 2
        + (data[:, :, 1].astype(float) - g) ** 2
        + (data[:, :, 2].astype(float) - b) ** 2
    )

    mask = dist < tolerance
    data[mask] = [0, 0, 0, 0]

    return Image.fromarray(data, "RGBA")


def process_spritesheet(input_path: str, char_key: str, bg_color: tuple[int, int, int], tolerance: int) -> None:
    """Main processing pipeline."""
    print(f"Processing {input_path} for character '{char_key}'")
    img = Image.open(input_path).convert("RGBA")
    print(f"  Input size: {img.size}")

    # Step 1: Chroma key removal
    print(f"  Removing background (color: {bg_color}, tolerance: {tolerance})")
    img = chroma_key(img, bg_color, tolerance)

    # Step 2: Calculate cell size from image dimensions
    cell_w = img.width // COLS
    cell_h = img.height // ROWS
    print(f"  Cell size: {cell_w}x{cell_h}")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Step 3: Extract each row and produce a horizontal strip
    for row_idx, state_name in enumerate(ANIM_STATES):
        strip = Image.new("RGBA", (FRAME_SIZE * COLS, FRAME_SIZE), (0, 0, 0, 0))

        for col_idx in range(COLS):
            x1 = col_idx * cell_w
            y1 = row_idx * cell_h
            x2 = x1 + cell_w
            y2 = y1 + cell_h

            frame = img.crop((x1, y1, x2, y2))

            # Resize to exactly FRAME_SIZE x FRAME_SIZE using NEAREST for pixel art
            frame = frame.resize((FRAME_SIZE, FRAME_SIZE), Image.NEAREST)

            strip.paste(frame, (col_idx * FRAME_SIZE, 0))

        out_path = OUTPUT_DIR / f"{char_key}-{state_name}.png"
        strip.save(out_path)
        print(f"    {state_name} -> {out_path} ({strip.size[0]}x{strip.size[1]})")

    print("Done!")


def main() -> None:
    parser = argparse.ArgumentParser(description="Process a Gemini-generated spritesheet with chroma keying")
    parser.add_argument("input", help="Path to the input spritesheet image")
    parser.add_argument("character", help="Character key (e.g., sausage, burger, bacon, cheese)")
    parser.add_argument("--bg-color", default="00FF00", help="Background color to remove as hex (default: 00FF00 = green)")
    parser.add_argument("--tolerance", type=int, default=80, help="Color distance tolerance for chroma keying (default: 80)")
    args = parser.parse_args()

    bg_rgb = hex_to_rgb(args.bg_color)
    process_spritesheet(args.input, args.character, bg_rgb, args.tolerance)


if __name__ == "__main__":
    main()
