#!/usr/bin/env python3
"""
Post-process a character spritesheet generated by Gemini.

Takes a 4x7 grid spritesheet with a green (#00FF00) chroma-key background and:
1. Removes the background via chroma keying (replaces with transparency)
2. Removes green fringe from edges of characters
3. Auto-trims transparent borders so frames tightly bound the character
4. Splits into per-state horizontal strip PNGs (4 frames each at 128x128)

Usage:
  python3 scripts/process_spritesheet.py <input_image> <character_key> [--bg-color RRGGBB] [--tolerance N]
"""

import argparse
from pathlib import Path

from PIL import Image, ImageFilter
import numpy as np

ANIM_STATES = ["idle", "walk", "punch", "kick", "jump", "block", "ko"]
COLS = 4
ROWS = 7
FRAME_SIZE = 128
OUTPUT_DIR = Path(__file__).resolve().parent.parent / "public" / "assets" / "sprites"


def hex_to_rgb(hex_str: str) -> tuple[int, int, int]:
    hex_str = hex_str.lstrip("#")
    return (int(hex_str[0:2], 16), int(hex_str[2:4], 16), int(hex_str[4:6], 16))


def chroma_key(img: Image.Image, bg_color: tuple[int, int, int], tolerance: int) -> Image.Image:
    """Replace pixels close to bg_color with transparency, then clean up green fringe."""
    rgba = img.convert("RGBA")
    data = np.array(rgba, dtype=np.float64)

    r, g, b = bg_color
    dist = np.sqrt(
        (data[:, :, 0] - r) ** 2
        + (data[:, :, 1] - g) ** 2
        + (data[:, :, 2] - b) ** 2
    )

    # Hard removal of background pixels
    mask = dist < tolerance
    data[mask] = [0, 0, 0, 0]

    # Desaturate green fringe on semi-transparent edge pixels
    # Pixels that are close-ish to green but not removed (fringe zone)
    fringe_mask = (dist >= tolerance) & (dist < tolerance * 1.8)
    fringe_mask &= data[:, :, 3] > 0  # only non-transparent
    fringe_mask &= data[:, :, 1] > data[:, :, 0]  # green-dominant
    fringe_mask &= data[:, :, 1] > data[:, :, 2]  # green-dominant

    # Reduce green channel on fringe pixels
    if np.any(fringe_mask):
        avg_rb = (data[fringe_mask, 0] + data[fringe_mask, 2]) / 2
        data[fringe_mask, 1] = np.minimum(data[fringe_mask, 1], avg_rb * 1.1)

    result = Image.fromarray(data.astype(np.uint8), "RGBA")
    return result


def auto_trim_frame(frame: Image.Image) -> Image.Image:
    """Trim transparent borders and re-center on a FRAME_SIZE x FRAME_SIZE canvas."""
    bbox = frame.getbbox()
    if bbox is None:
        return Image.new("RGBA", (FRAME_SIZE, FRAME_SIZE), (0, 0, 0, 0))

    cropped = frame.crop(bbox)
    cw, ch = cropped.size

    # Scale to fit FRAME_SIZE while maintaining aspect ratio, with small padding
    max_dim = FRAME_SIZE - 4  # 2px padding on each side
    scale = min(max_dim / cw, max_dim / ch)

    if scale < 1:
        new_w = int(cw * scale)
        new_h = int(ch * scale)
        cropped = cropped.resize((new_w, new_h), Image.NEAREST)
    else:
        new_w, new_h = cw, ch

    # Center on canvas
    canvas = Image.new("RGBA", (FRAME_SIZE, FRAME_SIZE), (0, 0, 0, 0))
    offset_x = (FRAME_SIZE - new_w) // 2
    offset_y = FRAME_SIZE - new_h - 2  # Anchor to bottom with 2px padding
    canvas.paste(cropped, (offset_x, offset_y))
    return canvas


def process_spritesheet(input_path: str, char_key: str, bg_color: tuple[int, int, int], tolerance: int) -> None:
    print(f"Processing {input_path} for character '{char_key}'")
    img = Image.open(input_path).convert("RGBA")
    print(f"  Input size: {img.size}")

    print(f"  Removing background (color: {bg_color}, tolerance: {tolerance})")
    img = chroma_key(img, bg_color, tolerance)

    cell_w = img.width // COLS
    cell_h = img.height // ROWS
    print(f"  Cell size: {cell_w}x{cell_h}")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    for row_idx, state_name in enumerate(ANIM_STATES):
        strip = Image.new("RGBA", (FRAME_SIZE * COLS, FRAME_SIZE), (0, 0, 0, 0))

        for col_idx in range(COLS):
            x1 = col_idx * cell_w
            y1 = row_idx * cell_h
            x2 = x1 + cell_w
            y2 = y1 + cell_h

            frame = img.crop((x1, y1, x2, y2))
            frame = auto_trim_frame(frame)
            strip.paste(frame, (col_idx * FRAME_SIZE, 0))

        out_path = OUTPUT_DIR / f"{char_key}-{state_name}.png"
        strip.save(out_path)
        print(f"    {state_name} -> {out_path}")

    print("Done!")


def main() -> None:
    parser = argparse.ArgumentParser(description="Process a Gemini-generated spritesheet with chroma keying")
    parser.add_argument("input", help="Path to the input spritesheet image")
    parser.add_argument("character", help="Character key (e.g., sausage, burger, bacon, cheese)")
    parser.add_argument("--bg-color", default="00FF00", help="Background color to remove as hex (default: 00FF00)")
    parser.add_argument("--tolerance", type=int, default=85, help="Color distance tolerance (default: 85)")
    args = parser.parse_args()

    bg_rgb = hex_to_rgb(args.bg_color)
    process_spritesheet(args.input, args.character, bg_rgb, args.tolerance)


if __name__ == "__main__":
    main()
